---
- name:  make node1 manager
  vars:
     NAME_contents: "{{ lookup('file', 'NAME') }}"
     TOKEN_contents: "{{ lookup('file', 'tmp/porthos/root/TOKEN') }}"
  hosts: node1
  gather_facts: False
  tasks:
  - user: name=muskateer shell=/bin/bash groups=docker append=yes
  - copy: src=tmp/porthos/tmp/node1.tgz  dest=/tmp/node1.tgz owner=root group=root mode=0644
  - copy: src=tmp/porthos/root/TOKEN dest=/root/TOKEN owner=root group=root mode=0644
  - copy: src=default/docker  dest=/etc/default/docker owner=root group=root mode=0644
  - script: node1.sh  creates=/root/.noded.txt
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
    when: hostvars[item].ansible_host is defined
    with_items: groups['all']
