---
- name:  make node1 manager
  vars:
     NAME_contents: "{{ lookup('file', 'NAME') }}"
     TOKEN_contents: "{{ lookup('file', 'TOKEN') }}"
  hosts: node1
  gather_facts: False
  tasks:
  - user: name=muskateer shell=/bin/bash groups=docker append=yes
  - copy: src=tmp/porthos/tmp/node1.tgz  dest=/tmp/node1.tgz owner=root group=root mode=0644
  - copy: src=tmp/porthos/root/TOKEN dest=/root/TOKEN owner=root group=root mode=0644
  - copy: src=default/docker  dest=/etc/default/docker owner=root group=root mode=0644
  - script: node1.sh  creates=/root/.noded.txt
  - name: node1 dockers
    docker:
      image: swarm
      command: join --addr=node1:2376 token://{{ TOKEN_contents }}
      state: reloaded
      restart_policy: always
