---
- name:  make swarm manager
  vars:
     NAME_contents: "{{ lookup('file', 'NAME') }}"
  hosts: swarm
  gather_facts: False
  tasks:
  - user: name=muskateer shell=/bin/bash groups=docker append=yes
  - copy: src=tmp/porthos/tmp/swarm.tgz  dest=/tmp/swarm.tgz owner=root group=root mode=0644
  - copy: src=default/docker  dest=/etc/default/docker owner=root group=root mode=0644
  - script: swarm.sh  creates=/root/.swarmed.txt
  - fetch: src=/root/TOKEN dest=tmp
